#!/bin/bash
update_python() {
    echo "update repository python"
    apt install python3 python3-pip -y
    sudo apt-get install build-essential checkinstall -y
    sudo apt-get install -y libreadline-gplv2-dev libncursesw5-dev libssl-dev \
        libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev
    cd /opt
    sudo wget https://www.python.org/ftp/python/3.8.12/Python-3.8.12.tgz
    sudo tar xzf Python-3.8.12.tgz
    cd Python-3.8.12
    sudo ./configure --enable-optimizations
    sudo make altinstall
}

main() {
    update_python
    cd /root/regis/shell
    chmod +x *
    mv * /usr/bin
    pip3.8 install -r /root/regis/requirements.txt
    pip3.8 install pyarmor
    cd 
    cat >/usr/bin/jhhhhh <<EOF
#!/bin/bash

cd 
python3.8 -m regis
EOF
    chmod +x /usr/bin/jhhhhh
    cat >/etc/systemd/system/regggg.service <<EOF
[Unit]
Description=FTVPN BOT 
Documentation=ftvpn
After=syslog.target network-online.target

[Service]
User=root
NoNewPrivileges=true
ExecStart=/usr/bin/jhhhhh

[Install]
WantedBy=multi-user.target

EOF
    cat >id <<EOF
TELEGRAM="t.me/rullpqh" #CONTOH t.me/rullpqh
WHATSAPP="wa.me/6281584099035"  #CONTOH wa.me/6281584099035
EOF
    cat >regis/var.txt <<EOF
BOT_TOKEN="6087646712:AAEg88w0QKfmYxULqlWOGhkudaNSURt_-iI"
ADMIN="5579282429"
SESSIONS="sdfddsferfreg" 
EOF
    systemctl daemon-reload
    systemctl stop regggg
    systemctl enable regggg
    systemctl start regggg
    systemctl restart regggg
    systemctl status regggg
}
main "$@"
