#!/bin/bash
clear
UUID=$(tr </dev/urandom -dc a-z | head -c8)
echo -e "   ┌──────────────────────────────────────────┐\033[0m"
echo -e "   │\033[0m\033[101m       BOT SIMPLE FTVPN TELEGRAM          \033[0m|\033[0m"
echo -e "   └──────────────────────────────────────────┘\033[0m"
echo -e "            Telegram Bot Setup menu"
echo -e "          make vpn in the telegram bot"
echo -e "──────────────────────────────────────────────────"
echo -e "   ${BLUE}get this value from @BotFather, required${NC}"
echo -e "    ${BLUE}take your id at @MissRose_bot,cmd (/id)${NC}"
echo -e "  ${BLUE}Tutorial? Join in the @fightertunnell group${NC}"
echo -e "        ==>> CTRL + C GO TO BACK <<=="
echo -e ""
echo -e "            CONTOH : t.me/rullpqh"
echo -e "        CONTOH : wa.me/6281584099035"
echo -e "          ────────────────────────"
read -e -p "Input your Bot Token : " TOKET
read -e -p "Input your Id Telegram : " IDTELE
read -e -p "Input your Telegram : " TELETT
read -e -p "Input your Whatsapp : " WHTSAPP
update_python() {
    echo "update repository python"
    apt install python3 python3-pip -y
    sudo apt-get install build-essential checkinstall -y
    sudo apt-get install -y libreadline-gplv2-dev libncursesw5-dev libssl-dev \
        libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev libffi-dev zlib1g-dev
    cd /opt
    sudo wget https://www.python.org/ftp/python/3.8.12/Python-3.8.12.tgz
    sudo tar xzf Python-3.8.12.tgz
    cd Python-3.8.12
    sudo ./configure --enable-optimizations
    sudo make altinstall
}

main() {
    update_python
    cd /root/regis/shell
    chmod +x *
    mv * /usr/bin
    pip3.8 install -r /root/regis/requirements.txt
    pip3.8 install pyarmor
    cd 
    cat >/usr/bin/jhhhhh <<EOF
#!/bin/bash

cd 
python3.8 -m regis
EOF
    chmod +x /usr/bin/jhhhhh
    cat >/etc/systemd/system/regggg.service <<EOF
[Unit]
Description=FTVPN BOT 
Documentation=ftvpn
After=syslog.target network-online.target

[Service]
User=root
NoNewPrivileges=true
ExecStart=/usr/bin/jhhhhh

[Install]
WantedBy=multi-user.target

EOF
    cat >id <<EOF
TELEGRAM="$TELETT" #CONTOH t.me/rullpqh
WHATSAPP="$WHTSAPP"  #CONTOH wa.me/6281584099035
EOF
    cat >regis/var.txt <<EOF
BOT_TOKEN="$TOKET"
ADMIN="$IDTELE"
SESSIONS="${UUID}"
EOF
    systemctl daemon-reload
    systemctl stop regggg
    systemctl enable regggg
    systemctl start regggg
    systemctl restart regggg
    systemctl status regggg
}
main "$@"
